export const traducciones = {
  es: {
    academia: "Academia de Idiomas",
    heroe: "HEROE DE LA PAZ BRIAN WILSON",
    lema: "Aprende Idiomas en Todo Nicaragua",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    emailPlaceholder: "ejemplo@academia.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Recordarme",
    olvidoContra: "¿Olvidaste la contraseña?",
    iniciarSesion: "Iniciar Sesión",
    noCuenta: "¿No tienes una cuenta?",
    crearCuenta: "Crear cuenta",
    pruebaBeta: "Prueba Beta",
    seleccionaRol: "Selecciona tu rol de prueba:",
    estudiante: "Estudiante",
    docente: "Docente",
    regresarManual: "Regresar al login manual",
    validando: "Validando...",
    accesoConcedido: "Acceso concedido. Cargando portal de ",
    accesoConcedidoBeta: "Acceso concedido (Beta). Cargando portal de ",
    alertaCredenciales: "Credenciales de prueba inválidas. Revisa las cuentas beta de abajo.",
    alertaCompletar: "Por favor, completa todos los campos.",

    // Tablero Estudiante
    portalEstudiante: "Portal Estudiante",
    miProgreso: "Mi Progreso",
    biblioteca: "Biblioteca",
    tareas: "Tareas",
    evaluaciones: "Evaluaciones",
    laboratorio: "Laboratorio",
    comunidad: "Comunidad",
    cerrarSesion: "Cerrar Sesión",
    expandirMenu: "Expandir menú",
    contraerMenu: "Contraer menú",
    abrirMenu: "Abrir menú",
    cerrarMenu: "Cerrar menú",
    menu: "Menú",
    idioma: "Idioma",

    // Progreso Estudiante
    panelInicio: "Panel de Inicio",
    bienvenido: "Bienvenido",
    bienvenidaSub: "Consulta tus novedades académicas y accede directamente a tus aulas.",
    misCursosActivos: "Mis Cursos Activos",
    misCursosAcademicos: "Mis Cursos Académicos",
    verTodo: "Ver todo",
    volverInicio: "← Volver al Inicio",
    buscarCurso: "Buscar por curso, nivel o profesor...",
    soloFavoritos: "Sólo Favoritos",
    mostrarTodos: "Mostrar Todos",
    vistaTarjeta: "Vista Tarjeta",
    vistaCuadricula: "Vista Cuadrícula",
    vistaLista: "Vista Lista",
    noCursos: "No se encontraron cursos",
    noCursosSub: "Intenta modificar los filtros de búsqueda o favoritos.",
    nivel: "NIVEL",
    avanceCurso: "Avance del Curso",
    avanceCiclo: "Avance del Ciclo",
    completado: "completado",
    ingresarAula: "Ingresar al Aula Virtual",
    ingresar: "Ingresar",
    prof: "Prof",
    quitarFavorito: "Quitar de favoritos",
    marcarFavorito: "Marcar como favorito",
    tablonRecurso: "Tablón de Recursos Compartidos",
    tablonSub: "Accede a las últimas guías, avisos y enlaces de apoyo compartidos por tus docentes.",
    visualizandoRecurso: "Visualizando Recurso Compartido",
    descargarArchivo: "Descargar Archivo",
    cerrarVista: "Cerrar Vista",
    simulacionDescarga: "Simulación: Iniciando descarga del archivo físico en su dispositivo.",
    simulacionReproduccion: "Simulación: Reproduciendo video de clase grabada...",

    // Docente – Menú
    portalDocente: "Portal Docente",
    inicioDocente: "Inicio",
    gestionContenido: "Contenido",
    actividades: "Actividades",
    calificaciones: "Calificaciones",
    analiticas: "Analíticas",
    comunicacion: "Comunicación",

    // Docente – Inicio
    bienvenidoDocente: "¡Bienvenido, Docente!",
    bienvenidaDocenteSub: "Gestiona tus grupos, publica contenido y haz seguimiento del progreso de tus estudiantes.",
    totalAlumnos: "Total Alumnos",
    clasesActivas: "Clases Activas",
    tareasPorCalificar: "Por Calificar",
    proximaClase: "Próxima Clase",
    gruposAsignados: "Grupos Asignados",
    alumnosInscritos: "alumnos",
    administrarAula: "Administrar",
    verDetalle: "Ver Detalle",
    accesosRapidos: "Accesos Rápidos",
    publicarRecurso: "Publicar Recurso",
    crearActividad: "Crear Actividad",
    revisarEntregas: "Revisar Entregas",
    agendarClase: "Agendar Clase",

    // Docente – Contenido (RF-07)
    gestionContenidoTitulo: "Gestión de Contenido",
    publicarNuevoRecurso: "Publicar Nuevo Recurso",
    tituloRecurso: "Título del Recurso",
    tipoRecurso: "Tipo",
    descripcionRecurso: "Descripción",
    tipoDocumento: "Documento PDF",
    tipoVideo: "Video",
    tipoEnlace: "Enlace Externo",
    tipoAudio: "Audio",
    grupoDestino: "Grupo Destino",
    todosLosGrupos: "Todos los Grupos",
    urlRecurso: "URL / Enlace",
    publicar: "Publicar",
    cancelar: "Cancelar",
    recursosPublicados: "Recursos Publicados",
    fechaPublicacion: "Publicado",
    vistasRecurso: "Vistas",
    editarRecurso: "Editar",
    eliminarRecurso: "Eliminar",
    sinRecursos: "No hay recursos publicados aún.",
    listaAlumnos: "Lista de Alumnos",
    buscarAlumno: "Buscar alumno...",
    nombreAlumno: "Nombre",
    progresoAlumno: "Progreso",
    estadoAlumno: "Estado",
    estadoActivo: "Activo",
    estadoInactivo: "Inactivo",
    accionAlumno: "Acción",
    verPerfil: "Ver Perfil",

    // Docente – Actividades (RF-08)
    actividadesTitulo: "Gestión de Actividades",
    nuevaTarea: "Nueva Tarea",
    nuevaEvaluacion: "Nueva Evaluación",
    tituloActividad: "Título de la Actividad",
    instrucciones: "Instrucciones",
    fechaLimite: "Fecha Límite",
    puntajeMaximo: "Puntaje Máximo",
    adjuntarArchivo: "Adjuntar Archivo (simulado)",
    crearTarea: "Crear Tarea",
    crearEvaluacion: "Crear Evaluación",
    actividadesActivas: "Actividades Activas",
    actividadesCerradas: "Actividades Cerradas",
    tipoTarea: "Tarea",
    tipoTest: "Test Interactivo",
    entregasRecibidas: "Entregas",
    verEntregas: "Ver Entregas",
    sinActividades: "No hay actividades en esta categoría.",
    pregunta: "Pregunta",
    agregarPregunta: "Agregar Pregunta",
    opcion: "Opción",
    respuestaCorrecta: "Respuesta Correcta",

    // Docente – Calificaciones (RF-09)
    calificacionesTitulo: "Calificaciones y Retroalimentación",
    entregasPendientes: "Entregas Pendientes",
    historialCalificaciones: "Historial",
    filtrarPorActividad: "Filtrar por actividad",
    filtrarPorGrupo: "Filtrar por grupo",
    todasLasActividades: "Todas las actividades",
    alumno: "Alumno",
    actividad: "Actividad",
    entregadoEl: "Entregado",
    puntaje: "Puntaje",
    comentario: "Retroalimentación",
    guardarCalificacion: "Guardar",
    exportarCalificaciones: "Exportar CSV",
    calificacionGuardada: "✓ Calificación guardada",
    sinEntregas: "No hay entregas pendientes.",
    calificado: "Calificado",
    pendiente: "Pendiente",
    verEntrega: "Ver Entrega",

    // Docente – Analíticas (RF-10)
    analiticasTitulo: "Analíticas de Rendimiento",
    rendimientoGrupal: "Rendimiento Grupal",
    progresoIndividual: "Progreso Individual",
    filtrarPeriodo: "Período",
    periodo7dias: "Últimos 7 días",
    periodo30dias: "Últimos 30 días",
    periodoSemestre: "Semestre",
    promedioGrupo: "Promedio del Grupo",
    mejorPuntaje: "Mejor Puntaje",
    peorPuntaje: "Puntaje Más Bajo",
    tasaEntrega: "Tasa de Entrega",
    estudianteCol: "Estudiante",
    promedioCol: "Promedio",
    entregasCol: "Entregas",
    tendencia: "Tendencia",
    tendenciaAlza: "↑ Al alza",
    tendenciaBaja: "↓ A la baja",
    tendenciaEstable: "→ Estable",

    // Docente – Comunicación (RF-11)
    comunicacionTitulo: "Comunicación",
    mensajes: "Mensajes",
    videoclases: "Videoclases",
    nuevoMensaje: "Nuevo Mensaje",
    destinatario: "Destinatario",
    asunto: "Asunto",
    cuerpoMensaje: "Mensaje",
    enviar: "Enviar",
    mensajesRecibidos: "Bandeja de Entrada",
    sinMensajes: "No hay mensajes.",
    responder: "Responder",
    agendarVideoclase: "Agendar Videoclase",
    tituloVideoclase: "Título de la Clase",
    fechaHora: "Fecha y Hora",
    enlaceReunion: "Enlace de Reunión",
    proximasVideoclases: "Próximas Videoclases",
    copiarEnlace: "Copiar Enlace",
    enlaceCopiado: "¡Copiado!",
    iniciarClase: "Iniciar Clase",
    sinVideoclases: "No hay videoclases agendadas.",
  },

    pt: {
    academia: "Academia de Idiomas",
    heroe: "HEROE DE LA PAZ BRIAN WILSON",
    lema: "Aprende Idiomas en Todo Nicaragua",
    emailLabel: "Correo Electrónico",
    passwordLabel: "Contraseña",
    emailPlaceholder: "ejemplo@academia.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Recordarme",
    olvidoContra: "¿Olvidaste la contraseña?",
    iniciarSesion: "Iniciar Sesión",
    noCuenta: "¿No tienes una cuenta?",
    crearCuenta: "Crear cuenta",
    pruebaBeta: "Prueba Beta",
    seleccionaRol: "Selecciona tu rol de prueba:",
    estudiante: "Estudiante",
    docente: "Docente",
    regresarManual: "Regresar al login manual",
    validando: "Validando...",
    accesoConcedido: "Acceso concedido. Cargando portal de ",
    accesoConcedidoBeta: "Acceso concedido (Beta). Cargando portal de ",
    alertaCredenciales: "Credenciales de prueba inválidas. Revisa las cuentas beta de abajo.",
    alertaCompletar: "Por favor, completa todos los campos.",

    // Tablero Estudiante
    portalEstudiante: "Portal Estudiante",
    miProgreso: "Mi Progreso",
    biblioteca: "Biblioteca",
    tareas: "Tareas",
    evaluaciones: "Evaluaciones",
    laboratorio: "Laboratorio",
    comunidad: "Comunidad",
    cerrarSesion: "Cerrar Sesión",
    expandirMenu: "Expandir menú",
    contraerMenu: "Contraer menú",
    abrirMenu: "Abrir menú",
    cerrarMenu: "Cerrar menú",
    menu: "Menú",
    idioma: "Idioma",

    // Progreso Estudiante
    panelInicio: "Panel de Inicio",
    bienvenido: "Bienvenido",
    bienvenidaSub: "Consulta tus novedades académicas y accede directamente a tus aulas.",
    misCursosActivos: "Mis Cursos Activos",
    misCursosAcademicos: "Mis Cursos Académicos",
    verTodo: "Ver todo",
    volverInicio: "← Volver al Inicio",
    buscarCurso: "Buscar por curso, nivel o profesor...",
    soloFavoritos: "Sólo Favoritos",
    mostrarTodos: "Mostrar Todos",
    vistaTarjeta: "Vista Tarjeta",
    vistaCuadricula: "Vista Cuadrícula",
    vistaLista: "Vista Lista",
    noCursos: "No se encontraron cursos",
    noCursosSub: "Intenta modificar los filtros de búsqueda o favoritos.",
    nivel: "NIVEL",
    avanceCurso: "Avance del Curso",
    avanceCiclo: "Avance del Ciclo",
    completado: "completado",
    ingresarAula: "Ingresar al Aula Virtual",
    ingresar: "Ingresar",
    prof: "Prof",
    quitarFavorito: "Quitar de favoritos",
    marcarFavorito: "Marcar como favorito",
    tablonRecurso: "Tablón de Recursos Compartidos",
    tablonSub: "Accede a las últimas guías, avisos y enlaces de apoyo compartidos por tus docentes.",
    visualizandoRecurso: "Visualizando Recurso Compartido",
    descargarArchivo: "Descargar Archivo",
    cerrarVista: "Cerrar Vista",
    simulacionDescarga: "Simulación: Iniciando descarga del archivo físico en su dispositivo.",
    simulacionReproduccion: "Simulación: Reproduciendo video de clase grabada...",

    // Docente – Menú
    portalDocente: "Portal Docente",
    inicioDocente: "Inicio",
    gestionContenido: "Contenido",
    actividades: "Actividades",
    calificaciones: "Calificaciones",
    analiticas: "Analíticas",
    comunicacion: "Comunicación",

    // Docente – Inicio
    bienvenidoDocente: "¡Bienvenido, Docente!",
    bienvenidaDocenteSub: "Gestiona tus grupos, publica contenido y haz seguimiento del progreso de tus estudiantes.",
    totalAlumnos: "Total Alumnos",
    clasesActivas: "Clases Activas",
    tareasPorCalificar: "Por Calificar",
    proximaClase: "Próxima Clase",
    gruposAsignados: "Grupos Asignados",
    alumnosInscritos: "alumnos",
    administrarAula: "Administrar",
    verDetalle: "Ver Detalle",
    accesosRapidos: "Accesos Rápidos",
    publicarRecurso: "Publicar Recurso",
    crearActividad: "Crear Actividad",
    revisarEntregas: "Revisar Entregas",
    agendarClase: "Agendar Clase",

    // Docente – Contenido (RF-07)
    gestionContenidoTitulo: "Gestión de Contenido",
    publicarNuevoRecurso: "Publicar Nuevo Recurso",
    tituloRecurso: "Título del Recurso",
    tipoRecurso: "Tipo",
    descripcionRecurso: "Descripción",
    tipoDocumento: "Documento PDF",
    tipoVideo: "Video",
    tipoEnlace: "Enlace Externo",
    tipoAudio: "Audio",
    grupoDestino: "Grupo Destino",
    todosLosGrupos: "Todos los Grupos",
    urlRecurso: "URL / Enlace",
    publicar: "Publicar",
    cancelar: "Cancelar",
    recursosPublicados: "Recursos Publicados",
    fechaPublicacion: "Publicado",
    vistasRecurso: "Vistas",
    editarRecurso: "Editar",
    eliminarRecurso: "Eliminar",
    sinRecursos: "No hay recursos publicados aún.",
    listaAlumnos: "Lista de Alumnos",
    buscarAlumno: "Buscar alumno...",
    nombreAlumno: "Nombre",
    progresoAlumno: "Progreso",
    estadoAlumno: "Estado",
    estadoActivo: "Activo",
    estadoInactivo: "Inactivo",
    accionAlumno: "Acción",
    verPerfil: "Ver Perfil",

    // Docente – Actividades (RF-08)
    actividadesTitulo: "Gestión de Actividades",
    nuevaTarea: "Nueva Tarea",
    nuevaEvaluacion: "Nueva Evaluación",
    tituloActividad: "Título de la Actividad",
    instrucciones: "Instrucciones",
    fechaLimite: "Fecha Límite",
    puntajeMaximo: "Puntaje Máximo",
    adjuntarArchivo: "Adjuntar Archivo (simulado)",
    crearTarea: "Crear Tarea",
    crearEvaluacion: "Crear Evaluación",
    actividadesActivas: "Actividades Activas",
    actividadesCerradas: "Actividades Cerradas",
    tipoTarea: "Tarea",
    tipoTest: "Test Interactivo",
    entregasRecibidas: "Entregas",
    verEntregas: "Ver Entregas",
    sinActividades: "No hay actividades en esta categoría.",
    pregunta: "Pregunta",
    agregarPregunta: "Agregar Pregunta",
    opcion: "Opción",
    respuestaCorrecta: "Respuesta Correcta",

    // Docente – Calificaciones (RF-09)
    calificacionesTitulo: "Calificaciones y Retroalimentación",
    entregasPendientes: "Entregas Pendientes",
    historialCalificaciones: "Historial",
    filtrarPorActividad: "Filtrar por actividad",
    filtrarPorGrupo: "Filtrar por grupo",
    todasLasActividades: "Todas las actividades",
    alumno: "Alumno",
    actividad: "Actividad",
    entregadoEl: "Entregado",
    puntaje: "Puntaje",
    comentario: "Retroalimentación",
    guardarCalificacion: "Guardar",
    exportarCalificaciones: "Exportar CSV",
    calificacionGuardada: "✓ Calificación guardada",
    sinEntregas: "No hay entregas pendientes.",
    calificado: "Calificado",
    pendiente: "Pendiente",
    verEntrega: "Ver Entrega",

    // Docente – Analíticas (RF-10)
    analiticasTitulo: "Analíticas de Rendimiento",
    rendimientoGrupal: "Rendimiento Grupal",
    progresoIndividual: "Progreso Individual",
    filtrarPeriodo: "Período",
    periodo7dias: "Últimos 7 días",
    periodo30dias: "Últimos 30 días",
    periodoSemestre: "Semestre",
    promedioGrupo: "Promedio del Grupo",
    mejorPuntaje: "Mejor Puntaje",
    peorPuntaje: "Puntaje Más Bajo",
    tasaEntrega: "Tasa de Entrega",
    estudianteCol: "Estudiante",
    promedioCol: "Promedio",
    entregasCol: "Entregas",
    tendencia: "Tendencia",
    tendenciaAlza: "↑ Al alza",
    tendenciaBaja: "↓ A la baja",
    tendenciaEstable: "→ Estable",

    // Docente – Comunicación (RF-11)
    comunicacionTitulo: "Comunicación",
    mensajes: "Mensajes",
    videoclases: "Videoclases",
    nuevoMensaje: "Nuevo Mensaje",
    destinatario: "Destinatario",
    asunto: "Asunto",
    cuerpoMensaje: "Mensaje",
    enviar: "Enviar",
    mensajesRecibidos: "Bandeja de Entrada",
    sinMensajes: "No hay mensajes.",
    responder: "Responder",
    agendarVideoclase: "Agendar Videoclase",
    tituloVideoclase: "Título de la Clase",
    fechaHora: "Fecha y Hora",
    enlaceReunion: "Enlace de Reunión",
    proximasVideoclases: "Próximas Videoclases",
    copiarEnlace: "Copiar Enlace",
    enlaceCopiado: "¡Copiado!",
    iniciarClase: "Iniciar Clase",
    sinVideoclases: "No hay videoclases agendadas.",
  },
  en: {
    academia: "Language Academy",
    heroe: "HEROES OF PEACE BRYAN WILSON",
    lema: "Learn Languages in All Nicaragua",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    emailPlaceholder: "example@academy.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Remember me",
    olvidoContra: "Forgot password?",
    iniciarSesion: "Sign In",
    noCuenta: "Don't have an account?",
    crearCuenta: "Create account",
    pruebaBeta: "Beta Test",
    seleccionaRol: "Select your test role:",
    estudiante: "Student",
    docente: "Teacher",
    regresarManual: "Go back to manual login",
    validando: "Validating...",
    accesoConcedido: "Access granted. Loading portal for ",
    accesoConcedidoBeta: "Access granted (Beta). Loading portal for ",
    alertaCredenciales: "Invalid test credentials. See beta accounts below.",
    alertaCompletar: "Please fill in all fields.",

    portalEstudiante: "Student Portal",
    miProgreso: "My Progress",
    biblioteca: "Library",
    tareas: "Tasks",
    evaluaciones: "Evaluations",
    laboratorio: "Laboratory",
    comunidad: "Community",
    cerrarSesion: "Sign Out",
    expandirMenu: "Expand menu",
    contraerMenu: "Collapse menu",
    abrirMenu: "Open menu",
    cerrarMenu: "Close menu",
    menu: "Menu",
    idioma: "Language",

    panelInicio: "Home Dashboard",
    bienvenido: "Welcome",
    bienvenidaSub: "Check your academic updates and access your classes directly.",
    misCursosActivos: "My Active Courses",
    misCursosAcademicos: "My Academic Courses",
    verTodo: "View all",
    volverInicio: "← Back to Home",
    buscarCurso: "Search by course, level or teacher...",
    soloFavoritos: "Only Favorites",
    mostrarTodos: "Show All",
    vistaTarjeta: "Card View",
    vistaCuadricula: "Grid View",
    vistaLista: "List View",
    noCursos: "No courses found",
    noCursosSub: "Try modifying the search or favorite filters.",
    nivel: "LEVEL",
    avanceCurso: "Course Progress",
    avanceCiclo: "Cycle Progress",
    completado: "completed",
    ingresarAula: "Enter Virtual Classroom",
    ingresar: "Enter",
    prof: "Teacher",
    quitarFavorito: "Remove from favorites",
    marcarFavorito: "Mark as favorite",
    tablonRecurso: "Shared Resources Board",
    tablonSub: "Access the latest guides, notices and support links shared by your teachers.",
    visualizandoRecurso: "Viewing Shared Resource",
    descargarArchivo: "Download File",
    cerrarVista: "Close View",
    simulacionDescarga: "Simulation: Starting physical file download on your device.",
    simulacionReproduccion: "Simulation: Playing recorded class video...",

    portalDocente: "Teacher Portal",
    inicioDocente: "Home",
    gestionContenido: "Content",
    actividades: "Activities",
    calificaciones: "Grades",
    analiticas: "Analytics",
    comunicacion: "Communication",

    bienvenidoDocente: "Welcome, Teacher!",
    bienvenidaDocenteSub: "Manage your groups, publish content and track your students' progress.",
    totalAlumnos: "Total Students",
    clasesActivas: "Active Classes",
    tareasPorCalificar: "To Grade",
    proximaClase: "Next Class",
    gruposAsignados: "Assigned Groups",
    alumnosInscritos: "students",
    administrarAula: "Manage",
    verDetalle: "View Detail",
    accesosRapidos: "Quick Access",
    publicarRecurso: "Publish Resource",
    crearActividad: "Create Activity",
    revisarEntregas: "Review Submissions",
    agendarClase: "Schedule Class",

    gestionContenidoTitulo: "Content Management",
    publicarNuevoRecurso: "Publish New Resource",
    tituloRecurso: "Resource Title",
    tipoRecurso: "Type",
    descripcionRecurso: "Description",
    tipoDocumento: "PDF Document",
    tipoVideo: "Video",
    tipoEnlace: "External Link",
    tipoAudio: "Audio",
    grupoDestino: "Target Group",
    todosLosGrupos: "All Groups",
    urlRecurso: "URL / Link",
    publicar: "Publish",
    cancelar: "Cancel",
    recursosPublicados: "Published Resources",
    fechaPublicacion: "Published",
    vistasRecurso: "Views",
    editarRecurso: "Edit",
    eliminarRecurso: "Delete",
    sinRecursos: "No resources published yet.",
    listaAlumnos: "Student List",
    buscarAlumno: "Search student...",
    nombreAlumno: "Name",
    progresoAlumno: "Progress",
    estadoAlumno: "Status",
    estadoActivo: "Active",
    estadoInactivo: "Inactive",
    accionAlumno: "Action",
    verPerfil: "View Profile",

    actividadesTitulo: "Activity Management",
    nuevaTarea: "New Task",
    nuevaEvaluacion: "New Evaluation",
    tituloActividad: "Activity Title",
    instrucciones: "Instructions",
    fechaLimite: "Due Date",
    puntajeMaximo: "Max Score",
    adjuntarArchivo: "Attach File (simulated)",
    crearTarea: "Create Task",
    crearEvaluacion: "Create Evaluation",
    actividadesActivas: "Active Activities",
    actividadesCerradas: "Closed Activities",
    tipoTarea: "Task",
    tipoTest: "Interactive Test",
    entregasRecibidas: "Submissions",
    verEntregas: "View Submissions",
    sinActividades: "No activities in this category.",
    pregunta: "Question",
    agregarPregunta: "Add Question",
    opcion: "Option",
    respuestaCorrecta: "Correct Answer",

    calificacionesTitulo: "Grades & Feedback",
    entregasPendientes: "Pending Submissions",
    historialCalificaciones: "History",
    filtrarPorActividad: "Filter by activity",
    filtrarPorGrupo: "Filter by group",
    todasLasActividades: "All activities",
    alumno: "Student",
    actividad: "Activity",
    entregadoEl: "Submitted",
    puntaje: "Score",
    comentario: "Feedback",
    guardarCalificacion: "Save",
    exportarCalificaciones: "Export CSV",
    calificacionGuardada: "✓ Grade saved",
    sinEntregas: "No pending submissions.",
    calificado: "Graded",
    pendiente: "Pending",
    verEntrega: "View Submission",

    analiticasTitulo: "Performance Analytics",
    rendimientoGrupal: "Group Performance",
    progresoIndividual: "Individual Progress",
    filtrarPeriodo: "Period",
    periodo7dias: "Last 7 days",
    periodo30dias: "Last 30 days",
    periodoSemestre: "Semester",
    promedioGrupo: "Group Average",
    mejorPuntaje: "Best Score",
    peorPuntaje: "Lowest Score",
    tasaEntrega: "Submission Rate",
    estudianteCol: "Student",
    promedioCol: "Average",
    entregasCol: "Submissions",
    tendencia: "Trend",
    tendenciaAlza: "↑ Rising",
    tendenciaBaja: "↓ Falling",
    tendenciaEstable: "→ Stable",

    comunicacionTitulo: "Communication",
    mensajes: "Messages",
    videoclases: "Video Classes",
    nuevoMensaje: "New Message",
    destinatario: "Recipient",
    asunto: "Subject",
    cuerpoMensaje: "Message",
    enviar: "Send",
    mensajesRecibidos: "Inbox",
    sinMensajes: "No messages.",
    responder: "Reply",
    agendarVideoclase: "Schedule Video Class",
    tituloVideoclase: "Class Title",
    fechaHora: "Date & Time",
    enlaceReunion: "Meeting Link",
    proximasVideoclases: "Upcoming Video Classes",
    copiarEnlace: "Copy Link",
    enlaceCopiado: "Copied!",
    iniciarClase: "Start Class",
    sinVideoclases: "No video classes scheduled.",
  },

  fr: {
    academia: "Académie des Langues",
    heroe: "HÉROS DE LA PAIX BRYAN WILSON",
    lema: "Apprenez les langues dans tout le Nicaragua",
    emailLabel: "Adresse E-mail",
    passwordLabel: "Mot de passe",
    emailPlaceholder: "exemple@academie.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Se souvenir de moi",
    olvidoContra: "Mot de passe oublié ?",
    iniciarSesion: "Se connecter",
    noCuenta: "Vous n'avez pas de compte ?",
    crearCuenta: "Créer un compte",
    pruebaBeta: "Test Bêta",
    seleccionaRol: "Sélectionnez votre rôle de test :",
    estudiante: "Étudiant",
    docente: "Enseignant",
    regresarManual: "Retour à la connexion manuelle",
    validando: "Validation en cours...",
    accesoConcedido: "Accès accordé. Chargement du portail de ",
    accesoConcedidoBeta: "Accès accordé (Bêta). Chargement du portail de ",
    alertaCredenciales: "Identifiants de test invalides. Voir les comptes bêta ci-dessous.",
    alertaCompletar: "Veuillez remplir tous les champs.",

    portalEstudiante: "Portail Étudiant",
    miProgreso: "Mon Progrès",
    biblioteca: "Bibliothèque",
    tareas: "Devoirs",
    evaluaciones: "Évaluations",
    laboratorio: "Laboratoire",
    comunidad: "Communauté",
    cerrarSesion: "Se déconnecter",
    expandirMenu: "Agrandir le menu",
    contraerMenu: "Réduire le menu",
    abrirMenu: "Ouvrir le menu",
    cerrarMenu: "Fermer le menu",
    menu: "Menu",
    idioma: "Langue",

    panelInicio: "Tableau de Bord",
    bienvenido: "Bienvenue",
    bienvenidaSub: "Consultez vos nouveautés académiques et accédez directement à vos cours.",
    misCursosActivos: "Mes Cours Actifs",
    misCursosAcademicos: "Mes Cours Académiques",
    verTodo: "Voir tout",
    volverInicio: "← Retour à l'accueil",
    buscarCurso: "Rechercher par cours, niveau ou enseignant...",
    soloFavoritos: "Uniquement Favoris",
    mostrarTodos: "Afficher tout",
    vistaTarjeta: "Vue Carte",
    vistaCuadricula: "Vue Grille",
    vistaLista: "Vue Liste",
    noCursos: "Aucun cours trouvé",
    noCursosSub: "Essayez de modifier les filtres de recherche ou de favoris.",
    nivel: "NIVEAU",
    avanceCurso: "Progression du cours",
    avanceCiclo: "Progression du cycle",
    completado: "terminé",
    ingresarAula: "Entrer dans la salle virtuelle",
    ingresar: "Entrer",
    prof: "Enseignant",
    quitarFavorito: "Retirer des favoris",
    marcarFavorito: "Ajouter aux favoris",
    tablonRecurso: "Tableau de Ressources Partagées",
    tablonSub: "Accédez aux derniers guides, avis et liens d'aide partagés par vos enseignants.",
    visualizandoRecurso: "Affichage de la ressource partagée",
    descargarArchivo: "Télécharger le fichier",
    cerrarVista: "Fermer la vue",
    simulacionDescarga: "Simulation: Lancement du téléchargement physique du fichier sur votre appareil.",
    simulacionReproduccion: "Simulation: Lecture de la vidéo du cours enregistré...",

    portalDocente: "Portail Enseignant",
    inicioDocente: "Accueil",
    gestionContenido: "Contenu",
    actividades: "Activités",
    calificaciones: "Notes",
    analiticas: "Analytique",
    comunicacion: "Communication",

    bienvenidoDocente: "Bienvenue, Enseignant !",
    bienvenidaDocenteSub: "Gérez vos groupes, publiez du contenu et suivez la progression de vos étudiants.",
    totalAlumnos: "Total Étudiants",
    clasesActivas: "Classes Actives",
    tareasPorCalificar: "À Noter",
    proximaClase: "Prochain Cours",
    gruposAsignados: "Groupes Assignés",
    alumnosInscritos: "étudiants",
    administrarAula: "Gérer",
    verDetalle: "Voir Détail",
    accesosRapidos: "Accès Rapides",
    publicarRecurso: "Publier Ressource",
    crearActividad: "Créer Activité",
    revisarEntregas: "Revoir Soumissions",
    agendarClase: "Planifier Cours",

    gestionContenidoTitulo: "Gestion du Contenu",
    publicarNuevoRecurso: "Publier Nouvelle Ressource",
    tituloRecurso: "Titre de la Ressource",
    tipoRecurso: "Type",
    descripcionRecurso: "Description",
    tipoDocumento: "Document PDF",
    tipoVideo: "Vidéo",
    tipoEnlace: "Lien Externe",
    tipoAudio: "Audio",
    grupoDestino: "Groupe Cible",
    todosLosGrupos: "Tous les Groupes",
    urlRecurso: "URL / Lien",
    publicar: "Publier",
    cancelar: "Annuler",
    recursosPublicados: "Ressources Publiées",
    fechaPublicacion: "Publié",
    vistasRecurso: "Vues",
    editarRecurso: "Modifier",
    eliminarRecurso: "Supprimer",
    sinRecursos: "Aucune ressource publiée pour l'instant.",
    listaAlumnos: "Liste des Étudiants",
    buscarAlumno: "Rechercher un étudiant...",
    nombreAlumno: "Nom",
    progresoAlumno: "Progrès",
    estadoAlumno: "Statut",
    estadoActivo: "Actif",
    estadoInactivo: "Inactif",
    accionAlumno: "Action",
    verPerfil: "Voir Profil",

    actividadesTitulo: "Gestion des Activités",
    nuevaTarea: "Nouvelle Tâche",
    nuevaEvaluacion: "Nouvelle Évaluation",
    tituloActividad: "Titre de l'Activité",
    instrucciones: "Instructions",
    fechaLimite: "Date Limite",
    puntajeMaximo: "Score Maximum",
    adjuntarArchivo: "Joindre Fichier (simulé)",
    crearTarea: "Créer Tâche",
    crearEvaluacion: "Créer Évaluation",
    actividadesActivas: "Activités Actives",
    actividadesCerradas: "Activités Fermées",
    tipoTarea: "Tâche",
    tipoTest: "Test Interactif",
    entregasRecibidas: "Soumissions",
    verEntregas: "Voir Soumissions",
    sinActividades: "Aucune activité dans cette catégorie.",
    pregunta: "Question",
    agregarPregunta: "Ajouter Question",
    opcion: "Option",
    respuestaCorrecta: "Bonne Réponse",

    calificacionesTitulo: "Notes et Retours",
    entregasPendientes: "Soumissions en Attente",
    historialCalificaciones: "Historique",
    filtrarPorActividad: "Filtrer par activité",
    filtrarPorGrupo: "Filtrer par groupe",
    todasLasActividades: "Toutes les activités",
    alumno: "Étudiant",
    actividad: "Activité",
    entregadoEl: "Soumis",
    puntaje: "Score",
    comentario: "Retour",
    guardarCalificacion: "Sauvegarder",
    exportarCalificaciones: "Exporter CSV",
    calificacionGuardada: "✓ Note sauvegardée",
    sinEntregas: "Aucune soumission en attente.",
    calificado: "Noté",
    pendiente: "En attente",
    verEntrega: "Voir Soumission",

    analiticasTitulo: "Analytique de Performance",
    rendimientoGrupal: "Performance du Groupe",
    progresoIndividual: "Progrès Individuel",
    filtrarPeriodo: "Période",
    periodo7dias: "7 derniers jours",
    periodo30dias: "30 derniers jours",
    periodoSemestre: "Semestre",
    promedioGrupo: "Moyenne du Groupe",
    mejorPuntaje: "Meilleur Score",
    peorPuntaje: "Score le Plus Bas",
    tasaEntrega: "Taux de Soumission",
    estudianteCol: "Étudiant",
    promedioCol: "Moyenne",
    entregasCol: "Soumissions",
    tendencia: "Tendance",
    tendenciaAlza: "↑ En hausse",
    tendenciaBaja: "↓ En baisse",
    tendenciaEstable: "→ Stable",

    comunicacionTitulo: "Communication",
    mensajes: "Messages",
    videoclases: "Vidéo-cours",
    nuevoMensaje: "Nouveau Message",
    destinatario: "Destinataire",
    asunto: "Sujet",
    cuerpoMensaje: "Message",
    enviar: "Envoyer",
    mensajesRecibidos: "Boîte de réception",
    sinMensajes: "Aucun message.",
    responder: "Répondre",
    agendarVideoclase: "Planifier Vidéo-cours",
    tituloVideoclase: "Titre du Cours",
    fechaHora: "Date et Heure",
    enlaceReunion: "Lien de Réunion",
    proximasVideoclases: "Prochains Vidéo-cours",
    copiarEnlace: "Copier le Lien",
    enlaceCopiado: "Copié !",
    iniciarClase: "Démarrer le Cours",
    sinVideoclases: "Aucun vidéo-cours planifié.",
  },

  de: {
    academia: "Sprachakademie",
    heroe: "FRIEDENSHELD BRYAN WILSON",
    lema: "Lernen Sie Sprachen in ganz Nicaragua",
    emailLabel: "E-Mail-Adresse",
    passwordLabel: "Passwort",
    emailPlaceholder: "beispiel@akademie.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Angemeldet bleiben",
    olvidoContra: "Passwort vergessen?",
    iniciarSesion: "Einloggen",
    noCuenta: "Haben Sie kein Konto?",
    crearCuenta: "Konto erstellen",
    pruebaBeta: "Beta-Test",
    seleccionaRol: "Wählen Sie Ihre Testrolle:",
    estudiante: "Student",
    docente: "Dozent",
    regresarManual: "Zurück zum manuellen Login",
    validando: "Validierung...",
    accesoConcedido: "Zugriff gewährt. Portal wird geladen für ",
    accesoConcedidoBeta: "Zugriff gewährt (Beta). Portal wird geladen für ",
    alertaCredenciales: "Ungültige Test-Anmeldedaten. Siehe Beta-Konten unten.",
    alertaCompletar: "Bitte füllen Sie alle Felder aus.",

    portalEstudiante: "Studentenportal",
    miProgreso: "Mein Fortschritt",
    biblioteca: "Bibliothek",
    tareas: "Aufgaben",
    evaluaciones: "Bewertungen",
    laboratorio: "Labor",
    comunidad: "Gemeinschaft",
    cerrarSesion: "Abmelden",
    expandirMenu: "Menü erweitern",
    contraerMenu: "Menü einklappen",
    abrirMenu: "Menü öffnen",
    cerrarMenu: "Menü schließen",
    menu: "Menü",
    idioma: "Sprache",

    panelInicio: "Startseite",
    bienvenido: "Willkommen",
    bienvenidaSub: "Überprüfen Sie Ihre akademischen Updates und greifen Sie direkt auf Ihre Kurse zu.",
    misCursosActivos: "Meine aktiven Kurse",
    misCursosAcademicos: "Meine akademischen Kurse",
    verTodo: "Alle anzeigen",
    volverInicio: "← Zurück zur Startseite",
    buscarCurso: "Suche nach Kurs, Niveau oder Dozent...",
    soloFavoritos: "Nur Favoriten",
    mostrarTodos: "Alle anzeigen",
    vistaTarjeta: "Kartenansicht",
    vistaCuadricula: "Rasteransicht",
    vistaLista: "Listenansicht",
    noCursos: "Keine Kurse gefunden",
    noCursosSub: "Versuchen Sie, die Such- oder Favoritenfilter zu ändern.",
    nivel: "NIVEAU",
    avanceCurso: "Kursfortschritt",
    avanceCiclo: "Zyklusfortschritt",
    completado: "abgeschlossen",
    ingresarAula: "Virtuellen Klassenraum betreten",
    ingresar: "Eintreten",
    prof: "Dozent",
    quitarFavorito: "Aus Favoriten entfernen",
    marcarFavorito: "Als Favorit markieren",
    tablonRecurso: "Gemeinsame Ressourcen-Tafel",
    tablonSub: "Greifen Sie auf die neuesten Leitfäden, Ankündigungen und Hilfelinks Ihrer Dozenten zu.",
    visualizandoRecurso: "Gemeinsame Ressource anzeigen",
    descargarArchivo: "Datei herunterladen",
    cerrarVista: "Ansicht schließen",
    simulacionDescarga: "Simulation: Physischer Dateidownload auf Ihrem Gerät wird gestartet.",
    simulacionReproduccion: "Simulation: Aufgenommenes Klassenvideo abspielen...",

    portalDocente: "Lehrerportal",
    inicioDocente: "Startseite",
    gestionContenido: "Inhalt",
    actividades: "Aktivitäten",
    calificaciones: "Noten",
    analiticas: "Analytik",
    comunicacion: "Kommunikation",

    bienvenidoDocente: "Willkommen, Dozent!",
    bienvenidaDocenteSub: "Verwalten Sie Ihre Gruppen, veröffentlichen Sie Inhalte und verfolgen Sie den Fortschritt Ihrer Studenten.",
    totalAlumnos: "Gesamtstudenten",
    clasesActivas: "Aktive Klassen",
    tareasPorCalificar: "Zu Benoten",
    proximaClase: "Nächste Klasse",
    gruposAsignados: "Zugewiesene Gruppen",
    alumnosInscritos: "Studenten",
    administrarAula: "Verwalten",
    verDetalle: "Details anzeigen",
    accesosRapidos: "Schnellzugriff",
    publicarRecurso: "Ressource veröffentlichen",
    crearActividad: "Aktivität erstellen",
    revisarEntregas: "Einreichungen überprüfen",
    agendarClase: "Klasse planen",

    gestionContenidoTitulo: "Inhaltsverwaltung",
    publicarNuevoRecurso: "Neue Ressource veröffentlichen",
    tituloRecurso: "Ressourcentitel",
    tipoRecurso: "Typ",
    descripcionRecurso: "Beschreibung",
    tipoDocumento: "PDF-Dokument",
    tipoVideo: "Video",
    tipoEnlace: "Externer Link",
    tipoAudio: "Audio",
    grupoDestino: "Zielgruppe",
    todosLosGrupos: "Alle Gruppen",
    urlRecurso: "URL / Link",
    publicar: "Veröffentlichen",
    cancelar: "Abbrechen",
    recursosPublicados: "Veröffentlichte Ressourcen",
    fechaPublicacion: "Veröffentlicht",
    vistasRecurso: "Aufrufe",
    editarRecurso: "Bearbeiten",
    eliminarRecurso: "Löschen",
    sinRecursos: "Noch keine Ressourcen veröffentlicht.",
    listaAlumnos: "Studentenliste",
    buscarAlumno: "Student suchen...",
    nombreAlumno: "Name",
    progresoAlumno: "Fortschritt",
    estadoAlumno: "Status",
    estadoActivo: "Aktiv",
    estadoInactivo: "Inaktiv",
    accionAlumno: "Aktion",
    verPerfil: "Profil anzeigen",

    actividadesTitulo: "Aktivitätsverwaltung",
    nuevaTarea: "Neue Aufgabe",
    nuevaEvaluacion: "Neue Bewertung",
    tituloActividad: "Aktivitätstitel",
    instrucciones: "Anweisungen",
    fechaLimite: "Fälligkeitsdatum",
    puntajeMaximo: "Maximale Punktzahl",
    adjuntarArchivo: "Datei anhängen (simuliert)",
    crearTarea: "Aufgabe erstellen",
    crearEvaluacion: "Bewertung erstellen",
    actividadesActivas: "Aktive Aktivitäten",
    actividadesCerradas: "Geschlossene Aktivitäten",
    tipoTarea: "Aufgabe",
    tipoTest: "Interaktiver Test",
    entregasRecibidas: "Einreichungen",
    verEntregas: "Einreichungen anzeigen",
    sinActividades: "Keine Aktivitäten in dieser Kategorie.",
    pregunta: "Frage",
    agregarPregunta: "Frage hinzufügen",
    opcion: "Option",
    respuestaCorrecta: "Richtige Antwort",

    calificacionesTitulo: "Noten & Feedback",
    entregasPendientes: "Ausstehende Einreichungen",
    historialCalificaciones: "Verlauf",
    filtrarPorActividad: "Nach Aktivität filtern",
    filtrarPorGrupo: "Nach Gruppe filtern",
    todasLasActividades: "Alle Aktivitäten",
    alumno: "Student",
    actividad: "Aktivität",
    entregadoEl: "Eingereicht",
    puntaje: "Punktzahl",
    comentario: "Feedback",
    guardarCalificacion: "Speichern",
    exportarCalificaciones: "CSV exportieren",
    calificacionGuardada: "✓ Note gespeichert",
    sinEntregas: "Keine ausstehenden Einreichungen.",
    calificado: "Benotet",
    pendiente: "Ausstehend",
    verEntrega: "Einreichung anzeigen",

    analiticasTitulo: "Leistungsanalytik",
    rendimientoGrupal: "Gruppenleistung",
    progresoIndividual: "Individueller Fortschritt",
    filtrarPeriodo: "Zeitraum",
    periodo7dias: "Letzte 7 Tage",
    periodo30dias: "Letzte 30 Tage",
    periodoSemestre: "Semester",
    promedioGrupo: "Gruppendurchschnitt",
    mejorPuntaje: "Beste Punktzahl",
    peorPuntaje: "Niedrigste Punktzahl",
    tasaEntrega: "Einreichungsrate",
    estudianteCol: "Student",
    promedioCol: "Durchschnitt",
    entregasCol: "Einreichungen",
    tendencia: "Trend",
    tendenciaAlza: "↑ Steigend",
    tendenciaBaja: "↓ Fallend",
    tendenciaEstable: "→ Stabil",

    comunicacionTitulo: "Kommunikation",
    mensajes: "Nachrichten",
    videoclases: "Videokurse",
    nuevoMensaje: "Neue Nachricht",
    destinatario: "Empfänger",
    asunto: "Betreff",
    cuerpoMensaje: "Nachricht",
    enviar: "Senden",
    mensajesRecibidos: "Posteingang",
    sinMensajes: "Keine Nachrichten.",
    responder: "Antworten",
    agendarVideoclase: "Videokurs planen",
    tituloVideoclase: "Kurstitel",
    fechaHora: "Datum & Uhrzeit",
    enlaceReunion: "Meeting-Link",
    proximasVideoclases: "Bevorstehende Videokurse",
    copiarEnlace: "Link kopieren",
    enlaceCopiado: "Kopiert!",
    iniciarClase: "Kurs starten",
    sinVideoclases: "Keine Videokurse geplant.",
  },

  it: {
    academia: "Accademia di Lingue",
    heroe: "EROI DELLA PACE BRYAN WILSON",
    lema: "Impara le lingue in tutto il Nicaragua",
    emailLabel: "Indirizzo E-mail",
    passwordLabel: "Password",
    emailPlaceholder: "esempio@accademia.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Ricordami",
    olvidoContra: "Password dimenticata?",
    iniciarSesion: "Accedi",
    noCuenta: "Non hai un account?",
    crearCuenta: "Crea un account",
    pruebaBeta: "Beta Test",
    seleccionaRol: "Seleziona il tuo ruolo di prova:",
    estudiante: "Studente",
    docente: "Docente",
    regresarManual: "Torna al login manuale",
    validando: "Validazione...",
    accesoConcedido: "Accesso concesso. Caricamento del portale per ",
    accesoConcedidoBeta: "Accesso concesso (Beta). Caricamento del portale per ",
    alertaCredenciales: "Credenziali di prova non valide. Vedi i conti beta qui sotto.",
    alertaCompletar: "Si prega di completare tutti i campi.",

    portalEstudiante: "Portale Studente",
    miProgreso: "Il Mio Progresso",
    biblioteca: "Biblioteca",
    tareas: "Compiti",
    evaluaciones: "Valutazioni",
    laboratorio: "Laboratorio",
    comunidad: "Comunità",
    cerrarSesion: "Disconnettersi",
    expandirMenu: "Espandi il menu",
    contraerMenu: "Riduci il menu",
    abrirMenu: "Apri il menu",
    cerrarMenu: "Chiudi il menu",
    menu: "Menu",
    idioma: "Lingua",

    panelInicio: "Pannello di Inizio",
    bienvenido: "Benvenuto",
    bienvenidaSub: "Controlla le tue novità accademiche e accedi direttamente alle tue aule.",
    misCursosActivos: "I Miei Corsi Attivi",
    misCursosAcademicos: "I Miei Corsi Accademici",
    verTodo: "Vedi tutto",
    volverInicio: "← Torna all'inizio",
    buscarCurso: "Cerca per corso, livello o docente...",
    soloFavoritos: "Solo Preferiti",
    mostrarTodos: "Mostra Tutti",
    vistaTarjeta: "Vista Scheda",
    vistaCuadricula: "Vista Griglia",
    vistaLista: "Vista Lista",
    noCursos: "Nessun corso trovato",
    noCursosSub: "Prova a modificare i filtri di ricerca o preferiti.",
    nivel: "LIVELLO",
    avanceCurso: "Avanzamento del Corso",
    avanceCiclo: "Avanzamento del Ciclo",
    completado: "completato",
    ingresarAula: "Entra nell'Aula Virtuale",
    ingresar: "Entra",
    prof: "Docente",
    quitarFavorito: "Rimuovi dai preferiti",
    marcarFavorito: "Segna come preferito",
    tablonRecurso: "Bacheca Risorse Condivise",
    tablonSub: "Accedi alle ultime guide, avvisi e link di supporto condivisi dai tuoi docenti.",
    visualizandoRecurso: "Visualizzazione Risorsa Condivisa",
    descargarArchivo: "Scarica File",
    cerrarVista: "Chiudi Vista",
    simulacionDescarga: "Simulazione: Avvio del download del file fisico sul tuo dispositivo.",
    simulacionReproduccion: "Simulazione: Riproduzione del video della lezione registrata...",

    portalDocente: "Portale Docente",
    inicioDocente: "Inizio",
    gestionContenido: "Contenuto",
    actividades: "Attività",
    calificaciones: "Voti",
    analiticas: "Analisi",
    comunicacion: "Comunicazione",

    bienvenidoDocente: "Benvenuto, Docente!",
    bienvenidaDocenteSub: "Gestisci i tuoi gruppi, pubblica contenuti e monitora il progresso dei tuoi studenti.",
    totalAlumnos: "Totale Studenti",
    clasesActivas: "Classi Attive",
    tareasPorCalificar: "Da Valutare",
    proximaClase: "Prossima Classe",
    gruposAsignados: "Gruppi Assegnati",
    alumnosInscritos: "studenti",
    administrarAula: "Gestisci",
    verDetalle: "Vedi Dettaglio",
    accesosRapidos: "Accessi Rapidi",
    publicarRecurso: "Pubblica Risorsa",
    crearActividad: "Crea Attività",
    revisarEntregas: "Rivedi Consegne",
    agendarClase: "Pianifica Lezione",

    gestionContenidoTitulo: "Gestione dei Contenuti",
    publicarNuevoRecurso: "Pubblica Nuova Risorsa",
    tituloRecurso: "Titolo della Risorsa",
    tipoRecurso: "Tipo",
    descripcionRecurso: "Descrizione",
    tipoDocumento: "Documento PDF",
    tipoVideo: "Video",
    tipoEnlace: "Link Esterno",
    tipoAudio: "Audio",
    grupoDestino: "Gruppo Target",
    todosLosGrupos: "Tutti i Gruppi",
    urlRecurso: "URL / Link",
    publicar: "Pubblica",
    cancelar: "Annulla",
    recursosPublicados: "Risorse Pubblicate",
    fechaPublicacion: "Pubblicato",
    vistasRecurso: "Visualizzazioni",
    editarRecurso: "Modifica",
    eliminarRecurso: "Elimina",
    sinRecursos: "Nessuna risorsa pubblicata ancora.",
    listaAlumnos: "Lista Studenti",
    buscarAlumno: "Cerca studente...",
    nombreAlumno: "Nome",
    progresoAlumno: "Progresso",
    estadoAlumno: "Stato",
    estadoActivo: "Attivo",
    estadoInactivo: "Inattivo",
    accionAlumno: "Azione",
    verPerfil: "Vedi Profilo",

    actividadesTitulo: "Gestione Attività",
    nuevaTarea: "Nuovo Compito",
    nuevaEvaluacion: "Nuova Valutazione",
    tituloActividad: "Titolo Attività",
    instrucciones: "Istruzioni",
    fechaLimite: "Scadenza",
    puntajeMaximo: "Punteggio Massimo",
    adjuntarArchivo: "Allega File (simulato)",
    crearTarea: "Crea Compito",
    crearEvaluacion: "Crea Valutazione",
    actividadesActivas: "Attività Attive",
    actividadesCerradas: "Attività Chiuse",
    tipoTarea: "Compito",
    tipoTest: "Test Interattivo",
    entregasRecibidas: "Consegne",
    verEntregas: "Vedi Consegne",
    sinActividades: "Nessuna attività in questa categoria.",
    pregunta: "Domanda",
    agregarPregunta: "Aggiungi Domanda",
    opcion: "Opzione",
    respuestaCorrecta: "Risposta Corretta",

    calificacionesTitulo: "Voti e Feedback",
    entregasPendientes: "Consegne in Sospeso",
    historialCalificaciones: "Cronologia",
    filtrarPorActividad: "Filtra per attività",
    filtrarPorGrupo: "Filtra per gruppo",
    todasLasActividades: "Tutte le attività",
    alumno: "Studente",
    actividad: "Attività",
    entregadoEl: "Consegnato",
    puntaje: "Punteggio",
    comentario: "Feedback",
    guardarCalificacion: "Salva",
    exportarCalificaciones: "Esporta CSV",
    calificacionGuardada: "✓ Voto salvato",
    sinEntregas: "Nessuna consegna in sospeso.",
    calificado: "Valutato",
    pendiente: "In sospeso",
    verEntrega: "Vedi Consegna",

    analiticasTitulo: "Analisi delle Prestazioni",
    rendimientoGrupal: "Prestazioni del Gruppo",
    progresoIndividual: "Progresso Individuale",
    filtrarPeriodo: "Periodo",
    periodo7dias: "Ultimi 7 giorni",
    periodo30dias: "Ultimi 30 giorni",
    periodoSemestre: "Semestre",
    promedioGrupo: "Media del Gruppo",
    mejorPuntaje: "Miglior Punteggio",
    peorPuntaje: "Punteggio Più Basso",
    tasaEntrega: "Tasso di Consegna",
    estudianteCol: "Studente",
    promedioCol: "Media",
    entregasCol: "Consegne",
    tendencia: "Tendenza",
    tendenciaAlza: "↑ In aumento",
    tendenciaBaja: "↓ In calo",
    tendenciaEstable: "→ Stabile",

    comunicacionTitulo: "Comunicazione",
    mensajes: "Messaggi",
    videoclases: "Videolezioni",
    nuevoMensaje: "Nuovo Messaggio",
    destinatario: "Destinatario",
    asunto: "Oggetto",
    cuerpoMensaje: "Messaggio",
    enviar: "Invia",
    mensajesRecibidos: "Posta in Arrivo",
    sinMensajes: "Nessun messaggio.",
    responder: "Rispondi",
    agendarVideoclase: "Pianifica Videolezione",
    tituloVideoclase: "Titolo della Lezione",
    fechaHora: "Data e Ora",
    enlaceReunion: "Link Riunione",
    proximasVideoclases: "Prossime Videolezioni",
    copiarEnlace: "Copia Link",
    enlaceCopiado: "Copiato!",
    iniciarClase: "Inizia Lezione",
    sinVideoclases: "Nessuna videolezione pianificata.",
  },

  ru: {
    academia: "Академия Языков",
    heroe: "ГЕРОЙ МИРА БРАЙАН УИЛСОН",
    lema: "Изучайте языки по всей Никарагуа",
    emailLabel: "Электронная почта",
    passwordLabel: "Пароль",
    emailPlaceholder: "primer@akademiya.com",
    passwordPlaceholder: "••••••••",
    recordarme: "Запомнить меня",
    olvidoContra: "Забыли пароль?",
    iniciarSesion: "Войти",
    noCuenta: "Нет учетной записи?",
    crearCuenta: "Создать аккаунт",
    pruebaBeta: "Бета-тест",
    seleccionaRol: "Выберите тестовую роль:",
    estudiante: "Студент",
    docente: "Преподаватель",
    regresarManual: "Вернуться к ручному входу",
    validando: "Проверка...",
    accesoConcedido: "Доступ разрешен. Загрузка портала для ",
    accesoConcedidoBeta: "Доступ разрешен (Бета). Загрузка портала для ",
    alertaCredenciales: "Неверные тестовые учетные данные. См. бета-аккаунты ниже.",
    alertaCompletar: "Пожалуйста, заполните все поля.",

    portalEstudiante: "Портал студента",
    miProgreso: "Мой прогресс",
    biblioteca: "Библиотека",
    tareas: "Задания",
    evaluaciones: "Оценки",
    laboratorio: "Лаборатория",
    comunidad: "Сообщество",
    cerrarSesion: "Выйти из системы",
    expandirMenu: "Развернуть меню",
    contraerMenu: "Свернуть меню",
    abrirMenu: "Открыть меню",
    cerrarMenu: "Закрыть меню",
    menu: "Меню",
    idioma: "Язык",

    panelInicio: "Панель управления",
    bienvenido: "Добро пожаловать",
    bienvenidaSub: "Проверяйте свои академические новости и переходите прямо к занятиям.",
    misCursosActivos: "Мои активные курсы",
    misCursosAcademicos: "Мои академические курсы",
    verTodo: "Показать все",
    volverInicio: "← Вернуться на главную",
    buscarCurso: "Поиск по курсу, уровню или преподавателю...",
    soloFavoritos: "Только избранное",
    mostrarTodos: "Показать все",
    vistaTarjeta: "Карточки",
    vistaCuadricula: "Сетка",
    vistaLista: "Список",
    noCursos: "Курсы не найдены",
    noCursosSub: "Попробуйте изменить поисковые или избранные фильтры.",
    nivel: "УРОВЕНЬ",
    avanceCurso: "Прогресс по курсу",
    avanceCiclo: "Прогресс по циклу",
    completado: "выполнено",
    ingresarAula: "Войти в виртуальный класс",
    ingresar: "Войти",
    prof: "Препод",
    quitarFavorito: "Удалить из избранного",
    marcarFavorito: "Добавить в избранное",
    tablonRecurso: "Доска общих ресурсов",
    tablonSub: "Получите доступ к последним руководствам, уведомлениям и справочным ссылкам ваших преподавателей.",
    visualizandoRecurso: "Просмотр общего ресурса",
    descargarArchivo: "Скачать файл",
    cerrarVista: "Закрыть просмотр",
    simulacionDescarga: "Симуляция: Начало скачивания файла на устройство.",
    simulacionReproduccion: "Симуляция: Воспроизведение видео записанного урока...",

    portalDocente: "Портал преподавателя",
    inicioDocente: "Главная",
    gestionContenido: "Контент",
    actividades: "Активности",
    calificaciones: "Оценки",
    analiticas: "Аналитика",
    comunicacion: "Общение",

    bienvenidoDocente: "Добро пожаловать, преподаватель!",
    bienvenidaDocenteSub: "Управляйте своими группами, публикуйте контент и отслеживайте прогресс студентов.",
    totalAlumnos: "Всего студентов",
    clasesActivas: "Активные классы",
    tareasPorCalificar: "На проверку",
    proximaClase: "Следующий класс",
    gruposAsignados: "Назначенные группы",
    alumnosInscritos: "студентов",
    administrarAula: "Управлять",
    verDetalle: "Подробнее",
    accesosRapidos: "Быстрый доступ",
    publicarRecurso: "Опубликовать ресурс",
    crearActividad: "Создать активность",
    revisarEntregas: "Проверить работы",
    agendarClase: "Запланировать урок",

    gestionContenidoTitulo: "Управление контентом",
    publicarNuevoRecurso: "Опубликовать новый ресурс",
    tituloRecurso: "Название ресурса",
    tipoRecurso: "Тип",
    descripcionRecurso: "Описание",
    tipoDocumento: "PDF документ",
    tipoVideo: "Видео",
    tipoEnlace: "Внешняя ссылка",
    tipoAudio: "Аудио",
    grupoDestino: "Целевая группа",
    todosLosGrupos: "Все группы",
    urlRecurso: "URL / Ссылка",
    publicar: "Опубликовать",
    cancelar: "Отменить",
    recursosPublicados: "Опубликованные ресурсы",
    fechaPublicacion: "Опубликовано",
    vistasRecurso: "Просмотры",
    editarRecurso: "Редактировать",
    eliminarRecurso: "Удалить",
    sinRecursos: "Ресурсы ещё не опубликованы.",
    listaAlumnos: "Список студентов",
    buscarAlumno: "Поиск студента...",
    nombreAlumno: "Имя",
    progresoAlumno: "Прогресс",
    estadoAlumno: "Статус",
    estadoActivo: "Активный",
    estadoInactivo: "Неактивный",
    accionAlumno: "Действие",
    verPerfil: "Просмотреть профиль",

    actividadesTitulo: "Управление активностями",
    nuevaTarea: "Новое задание",
    nuevaEvaluacion: "Новая оценка",
    tituloActividad: "Название активности",
    instrucciones: "Инструкции",
    fechaLimite: "Срок сдачи",
    puntajeMaximo: "Максимальный балл",
    adjuntarArchivo: "Прикрепить файл (симуляция)",
    crearTarea: "Создать задание",
    crearEvaluacion: "Создать оценку",
    actividadesActivas: "Активные активности",
    actividadesCerradas: "Закрытые активности",
    tipoTarea: "Задание",
    tipoTest: "Интерактивный тест",
    entregasRecibidas: "Работы",
    verEntregas: "Просмотреть работы",
    sinActividades: "Нет активностей в этой категории.",
    pregunta: "Вопрос",
    agregarPregunta: "Добавить вопрос",
    opcion: "Вариант",
    respuestaCorrecta: "Правильный ответ",

    calificacionesTitulo: "Оценки и отзывы",
    entregasPendientes: "Работы на проверке",
    historialCalificaciones: "История",
    filtrarPorActividad: "Фильтр по активности",
    filtrarPorGrupo: "Фильтр по группе",
    todasLasActividades: "Все активности",
    alumno: "Студент",
    actividad: "Активность",
    entregadoEl: "Сдано",
    puntaje: "Балл",
    comentario: "Отзыв",
    guardarCalificacion: "Сохранить",
    exportarCalificaciones: "Экспорт CSV",
    calificacionGuardada: "✓ Оценка сохранена",
    sinEntregas: "Нет работ на проверке.",
    calificado: "Оценено",
    pendiente: "Ожидает",
    verEntrega: "Просмотреть работу",

    analiticasTitulo: "Аналитика успеваемости",
    rendimientoGrupal: "Успеваемость группы",
    progresoIndividual: "Индивидуальный прогресс",
    filtrarPeriodo: "Период",
    periodo7dias: "Последние 7 дней",
    periodo30dias: "Последние 30 дней",
    periodoSemestre: "Семестр",
    promedioGrupo: "Средний балл группы",
    mejorPuntaje: "Лучший балл",
    peorPuntaje: "Низший балл",
    tasaEntrega: "Процент сдачи",
    estudianteCol: "Студент",
    promedioCol: "Средний балл",
    entregasCol: "Работы",
    tendencia: "Тенденция",
    tendenciaAlza: "↑ Растёт",
    tendenciaBaja: "↓ Снижается",
    tendenciaEstable: "→ Стабильно",

    comunicacionTitulo: "Общение",
    mensajes: "Сообщения",
    videoclases: "Видеоуроки",
    nuevoMensaje: "Новое сообщение",
    destinatario: "Получатель",
    asunto: "Тема",
    cuerpoMensaje: "Сообщение",
    enviar: "Отправить",
    mensajesRecibidos: "Входящие",
    sinMensajes: "Нет сообщений.",
    responder: "Ответить",
    agendarVideoclase: "Запланировать видеоурок",
    tituloVideoclase: "Название урока",
    fechaHora: "Дата и время",
    enlaceReunion: "Ссылка на встречу",
    proximasVideoclases: "Предстоящие видеоуроки",
    copiarEnlace: "Копировать ссылку",
    enlaceCopiado: "Скопировано!",
    iniciarClase: "Начать урок",
    sinVideoclases: "Видеоуроки не запланированы.",
  },
};
